### ISSUE TITLE
Katalóg požiadaviek

### ISSUE THREAD

**Issue by SimonDrastich** [TIS2019-FMFI/syncfile-editing#1]
15.10. je deadline a P.Petrovič nám to môže ešte vrátiť naspäť takže to treba odovzdať čo najskôr keby mal pripomienky aby sme ich stihli zapracovať.

**Comment by pavelpetrovic** [comment]
dakujem za navrh KP. 
dajte pozor, aby bol dokument gramaticky spravny a bez preklepov (pouzite spell-check), napr. "dokumnet" alebo "sa moze vzajomne pomahat", "do predu, do zadu", "tolko krat", "pouzivatelia ktory". 
udrzujte jednotnu terminologiu, ked je to raz synchronizacny subor, tak druhy raz to nemoze byt synchronizovany subor.
k samotnym poziadavkam:
3.1.1 je kombinovana poziadavka, treba ju rozbit na atomicke, kazda jednotlivost ma byt v samostatnej ocislovanej poziadavke
3.1.6. Taktiez pre ulahcenie prace vyraznit blok v ktorom sa momentalne pouzvatel nachadza.
Tento blok by mal byt READ-ONLY => nezrozumitelna, nejednoznacna poziadavka. nie je jasne, co znamena, "pouzivatel sa nachadza v bloku", nie je jasne, co znamena, ze je read-only, ostatne casti textu nie su read-only? preco? tiez nie je jasne, ako sa vlastne text ma zobrazit.
3.1.7 rozpiste do samostatnych poziadaviek. lepsie vysvetlite ako bude spajat bloky, najma ak su nesuvisle.
3.1.8. ak blok nema casovu znacku, je uz vobec blok? nerozumiem.
3.1.9. upresnite ako sa tie znacky budu posuvat. v texte vyssie mate, ze ide o stotiny sekund, tu sa pise o sekundach (konflikt, nejednoznacnost), asi by bolo dost nepohodlne, keby to musel posuvat vzdy po stotinkach, ale mat stotinkovu presnost by bolo fajn, ako to teda bude fungovat? sformulujte to jednoznacne a jasne.
Celkovo je v dokumente zmatok medzi blokmi a casovymi znackami. Moze mat jeden blok viacero casovych znaciek? co to znamena? ako to je ked blok vznikol spojenim nesuvislych blokov? treba to lepsie vysvetlit.
v 3.3. by som ocenil, keby ste sa vyjadrili k tomu, ako sa bude system spravat na rozlicnych rozliseniach - ak si to otvori pouzivatel na monitore s rozlisenim 5000x4000 bude to mrnave a ked si to otvori na 800x600 tak sa k niektorym tlacidlam nedostane, lebo budu za hranicou obrazovky?
vyrobte, prosim, aktualizovanu verziu a znovu mi ju poslite na kontrolu, zatial to neposielajte svojmu zadavatelovi, dakujem.

**Comment by pavelpetrovic** [comment]
dakujem za aktualizaciu KP.
Tu su este moje pripomienky, prosim, vsetky ich vycerpavajuco a dosledne zapracujte do KP. Ked to bude hotove, potom mozete vysledny KP poslat zadavatelovi a poziadat ho, aby si tu verziu dokladne prestudoval a dal k tomu spatnu vazbu, co chyba a co treba upravit, lebo podla neho budete system navrhovat a vyvijat:

* "Bloky urcuje používatel priamo v skripte v cudzom jazyku v lubovolnom textovom editore (mimo aplikácie Media Block Player)."
vyzera byt v konflikte s:
"Na obrazovke bude mat textové okno v ktorom bude text delit na bloky pomocou editovacej funkcie."
* používatelia ktorý
* súborou
* "urcený len pre desktop použitie." => nie je jasne, co sa mysli pod desktop pouzitie
* "pracovat aj off-line" => nie je jasne, co presne myslite pod off-line
* 3.1,7 pridavat skipped sa da iba za posledny oznaceny blok alebo aj medzi dva uz oznacene bloky? nie je to jasne z textu
* 3.1.8 nerozumiem. doteraz som si myslel, ze skipped su len v audio tracku, tu sa dozvedam, ze skipped mozu byt aj casti textu? prosim jednoznacne v texte vysvetlit (na vsetkych relevantnych miestach, nielen tu)
a este: zobrazit text => aplikacia zobrazuje
* 3.1.9 zvyraznit => aplikacia zvyraznuje
* 3.1.10 nie je jasne, ci sa to tyka aj blokov s uz vytvorenou audio znackou a ak ano, co sa deje, ak je medzi nimi skipped (ak sa take daju spajat, co tiez nie je jasne)
* 3.1.11 ak este nema casovu znacku, nie je mozne sa posunut na predchadzajuci? preco?
* 3.1.12. "o používatelom zvolenú casovú jednotku" - co to je? ako to urobi? ako ju urci?
* 3.3. co su to "bázy"?
* 3.3 mp3 nie je mozne z aplikacie stiahnut?

**Comment by pavelpetrovic** [comment]
citame si novu verziu KP, ostali uz len minimalne drobnosti:
 - 3.1.6: ľubovoľnému vybranému
    hlasujem za zrusenie slova "znova"
    na koniec pridat: ak aj predchadzajuci blok ma priradenu casovu znacku
 - 3.1.7. chýba možnosť urobiť skip na začiatku nahrávky
 - 3.1.8. zo ScriptFile = text zo ScriptFile, chyba info o podciarkovani uz priradenych blokov a tazko sa hada, co sa tym chce povedat, neda sa presnejsie-podrobnejsie vysvetlit?
 - 3.1.9  ukazuje pre aktualny blok aj polohu v audio alebo iba v texte?
 - 3.1.10. rozdelte to na atomicke poziadavky
   -  rozdelit editovaný blok na dva bloky
    => ako? napisanim zvislej | ?   a co ak tam da dve take?
      prosim pridat, ze rozdelenim sa prva cast stava novym aktualnym blokom
   - spojit vybraný blok s následujúcim textovým blokom 
    => znamena to, ze sa menia aj audio bloky? spajaju sa?
   - Ak blok ktorý rozdelujeme na dva už má casovú stopu tak bude musiet používatel pridat cas v ktorom sa majú rozdelit.
     => navrhujem vypustit tuto vetu a priradovanie casovej znacky robit len jednym sposobom pri editovani aktualneho bloku
 - 3.1.12.  milisekunda je 0.001 ale v casti 2 bolo 0.01

- chyba informacia o stlaceni tlacidla Save/Cancel na konci

- text v casti 3 by mali byt vety, v ktorych najdem aj podmet aj prisudok.

- niekde v texte by malo byt napisane, ze paralelne jazyky sa neriesia a musi si ich zosynchronizovat pouzivatel sam v externom editore

po dokladnom zapracovani pripomienok prosim poslat zadavatelovi s tym, ze nech sa k tomu podrobne vyjadri, lebo podla tohto to budete programovat.

**Comment by SimonDrastich** [comment]
Zapracované všetky pripomienky, schválené zadávateľom.
