### ISSUE TITLE
Spravovanie SyncFile dát

### ISSUE THREAD

**Issue by michalhorvath** [TIS2019-FMFI/syncfile-editing#10]
Definovanie, implementácia a odtestovanie triedy SyncFileEditorData podľa návrhu.

Pred implementovaním je potreba definovať triedy BlocksData a AudioPlayer, viz issues https://github.com/TIS2019-FMFI/syncfile-editing/issues/8 a https://github.com/TIS2019-FMFI/syncfile-editing/issues/9 .

**Comment by michalhorvath** [comment]
Do navrhu som pre triedu `BlocksEditor` pridal metodu `getCurrentBlockIndex(): Number`. 

Metoda `getTextOfAllBlocks(): String` mala rovnaku funkciu ako metoda `getScriptFileData(): String`, ale teraz som ju zmenil na `getTextOfAllBlocks(): [String]`. Bude sluzit pre vykreslenie textu do okna v editore kde sa bude farbou oznacovat, ktory block je vyznaceny. Skipped block bud nechaj prazdny String, null, undefined alebo text "<Skipped>".

**Comment by SimonDrastich** [comment]
Ok
