### ISSUE TITLE
Implementovanie pouzivatelskeho rozhrania

### ISSUE THREAD

**Issue by michalhorvath** [TIS2019-FMFI/syncfile-editing#14]
Vytvorit html pre vsetky stranky. Kod html sa vlozi do ViewController tried do metod renderHtml(html). Je potreba najprv definovat triedy ViewController, issue #12.

**Comment by michalhorvath** [comment]
Vytvor si branch z develop/issue12, kde som triedy `FilesPickerViewController`, `SyncFileEditViewController`, `EditBlockViewController` a `SyncFileDownloadViewController` inicializoval. Kod vkladaj do metod `renderHtml(): void`.

**Comment by SimonDrastich** [comment]
GUI v návrhu aj v HTML prehodiť remove skipped interval a skip interval. Pridať naspäť Cancel button a Edit block premenovať na pôvodný názov.

**Comment by SimonDrastich** [comment]
Ok
