### ISSUE TITLE
Návrh implementácie

### ISSUE THREAD

**Issue by andreahajna** [TIS2019-FMFI/syncfile-editing#2]

**Comment by pavelpetrovic** [comment]
dakujem za dokument, tu su pripomienky:

* pri  kniziciach, ktore sa pouzivaju, by mohlo byt napisane, ktore funkcie z nich a naco pouzite, napr. aj ako pristupujete k mysql z php a preco
* datovy model: potrebuje popis - kazda tabulka a kazde pole, idealne priamo do DB
* 3.2.2 " su namiesto |
* pozor na UTF-8 s BOM?
* 3.2.3 presny format a priklad
* 3.3. prosim rozpisat presne format requestov a responsov pre komunikaciu client-server
* 3.3. prosim vysvetlit ako a kde presne sa pouziva base64
* 5.1.2 rozvit a naopak 5.1.3 je samozrejme, netreba pisat take veci
namet: oddelit spravu zoznamu blokov od kontrolerov

**Comment by pavelpetrovic** [comment]
- prosim nevysvetlovat UML v dokumente
- triedny diagram ma potencial na vylepsenie, zakladny princip je dekompozicia podla dat nie podla funkcionality
