### ISSUE TITLE
Otestovať syncFileEditViewController

### ISSUE THREAD

**Issue by RobertStern** [TIS2019-FMFI/syncfile-editing#29]

**Comment by michalhorvath** [comment]
V ktorej branch je aktualna verzia? develop/finals?

Upravil som funkciu `presentNextController()`, pretoze tam bola povodna verzia.

V metodach, ktore si uz finalne implementoval, mozes odstranit TODOs.

Velmi dobre si spravil to disable tlacidiel pri pocuvani. Mozno by bolo dobre disable accept tlacidlo aj na zaciatku podobne ako sa disable po priradeni casu. Teraz to vyhodi vynimku, takze funkcionalita je ok aj teraz. Ale velmi sa mi to paci ako si to spravil.

**Comment by SimonDrastich** [comment]
Testing je hotový, už len odoslať zadávateľovy.
