### ISSUE TITLE
Návrh používateľského rozhrania

### ISSUE THREAD

**Issue by andreahajna** [TIS2019-FMFI/syncfile-editing#5]

**Comment by RobertStern** [comment]
[GUI_JK_ada.docx](https://github.com/TIS2019-FMFI/syncfile-editing/files/3818499/GUI_JK_ada.docx)

**Comment by SimonDrastich** [comment]
Návrh používateľského rozhrania schválený mentorom.

**Comment by pavelpetrovic** [comment]
moj navrh:
- Save + Exit a  CANCEL spojit do jedneho close
- je tam potencial pre vylepsienie ux
- napr. graficke ikonky s tooltipmi, alebo rozdelenie logickejsie na jednotlive panely buttonov, ktore suvisia
