### ISSUE TITLE
Bug 6: After SPLIT the ending time-mark is lost

### ISSUE THREAD

**Issue by michalhorvath** [TIS2019-FMFI/syncfile-editing#58]
Bug 6: After SPLIT the ending time-mark is lost
Choose test15.mp3 and test21.txt (attached) >
START CREATING  >
Play block "raz dva" > STOP > ACCEPT >
move LEFT > EDIT BLOCK > insert | between raz and dva >
APPLY EDITED CHANGES :
AS IS: block "dva" lost its time-mark
SHOULD BE: block "dva" keeps the time-mark (end of former block "raz
dva")

[test21.txt](https://github.com/TIS2019-FMFI/syncfile-editing/files/4142734/test21.txt)
[test15.mp3](https://bit.ly/2uVWIqA)

**Comment by SimonDrastich** [comment]
Done
