### ISSUE TITLE
Bug 7: On <Skipped> button [ACCEPT] should be disabled

### ISSUE THREAD

**Issue by michalhorvath** [TIS2019-FMFI/syncfile-editing#59]
Este som zdokumentoval problem s upravou time-marku <Skipped> intervalu. Zasadne by mal byt povoleny len [SKIPPED INTERVAL] a nie [ACCEPT]. Vedie to k problemom popisanym nizsie. Je to o aktivacii buttonov v roznych stavoch, ako som uz pisal pred casom a specifikoval v EditSyncFile_states_buttons.xlsx (znovu prilozeny).

<pre>
Bug 7: On <Skipped> button [ACCEPT] should be disabled
Choose test15.mp3 and test19.txt (attached) > START CREATING >
PLAY/PAUSE and ACCEPT blocks raz, dva, tri >
PLAY/PAUSE sound "blbost" > SKIP INTERVAL >
PLAY/PAUSE and ACCEPT blocks styri, pat >
move LEFT to <Skipped> to adjust the time-mark  >
PLAY/PAUSE sound "blbost" :
   AS IS:     [ACCEPT] is enabled,  [SKIP INTERVAL] is disabled
   SHOULD BE: [ACCEPT] is disabled, [SKIP INTERVAL] is enabled
> click [-] or [+] :
   AS IS: both [ACCEPT] and [SKIP INTERVAL] are enabled
   SHOULD BE: [ACCEPT] is disabled and [SKIP INTERVAL] is enabled
> click [SKIP INTERVAL] :
   AS IS: another <Skipped> is added : raz | dva | tri | <Skipped> | <Skipped> | styri | pat
   SHOULD BE: the existing <Skipped> interval time-mark is adjusted, no other <Skipped> should be added
</pre>

[test19.txt](https://github.com/TIS2019-FMFI/syncfile-editing/files/4142742/test19.txt)
[test15.mp3](https://bit.ly/2uVWIqA)

**Comment by SimonDrastich** [comment]
Funguje
