### ISSUE TITLE
drobnost

### ISSUE THREAD

**Issue by pavelpetrovic** [TIS2019-FMFI/syncfile-editing#70]
este sa mi stalo to, ze ked som dal merge na poslednom bloku, tak namiesto toho, aby povedalo, ze to nejde, vyskocilo okienko s textom:

TypeError: this.blocks[(this.currentBlockIndex + 1)] is undefined

nezabudnite potom, prosim, zrusit ostatne branche okrem master branch.

**Comment by SimonDrastich** [comment]
Hneď opravím a branch docs máme tiež vymazať?

**Comment by pavelpetrovic** [comment]
ten prosim zachovajte, dakujem.
