### ISSUE TITLE
Implementácia tried pre editáciu SyncFile

### ISSUE THREAD

**Issue by michalhorvath** [TIS2019-FMFI/syncfile-editing#8]
Definovať, implementovať a odtestovať triedy Block a BlocksEditor.

ScriptFileData a SyncFileData v konštruktore triedy BlocksEditor sú neparsované texty súborov ScriptFile a SyncFile. Je potrebné vyriešiť prípad ak sa BlocksEditor nedá vytvoriť, napr. výnimkou.

**Comment by SimonDrastich** [comment]
Vyhodiť upozornenie o viacnásobnéj pipline vedľa seba a upozorniť  používateľa na zmenu ||| -> |.

**Comment by michalhorvath** [comment]
> Vyhodiť upozornenie o viacnásobnéj pipline vedľa seba a upozorniť používateľa na zmenu ||| -> |.

Upozornenie nebude praktické robiť cez výnimku, pretože ak sa v konštruktore vyhodí výnimka, tak sa objekt nevytvorí.

**Comment by SimonDrastich** [comment]
To je pravda, ale ja v konštruktere iba nainicializujem objekty.

Potom robím init() v ktorom inicializujem už reálne bloky aj z ich časmi. Môžem to spraviť tam s tým že vykoná zmenu ||| -> | ak tam boli a až potom vyhodí výnimku. Zmena je aj tak iba v našom editore a používateľ to aj tak buď bude musieť akceptovať alebo s tým spraviť niečo sám a dočasne odísť.

**Comment by SimonDrastich** [comment]
Výnimky mám zatiaľ  dočasne v slovenčine ale predpokladám že keď už to budeme ladiť tak ich relevantne prepíšeme na angličtinu.

**Comment by SimonDrastich** [comment]
Ok
