### ISSUE TITLE
Prehrávanie audia

### ISSUE THREAD

**Issue by michalhorvath** [TIS2019-FMFI/syncfile-editing#9]
Definovanie, implementovanie a odtestovanie triedy AudioPlayer podľa návrhu.

Pozn.: Ako pomôcka môže poslúžiť trieda Player s pôvodnej aplikácie. Trieda AudioPlayer ale triedu Player nepredefinováva, trieda Player je potrebné pri prehrávaní, preto triedu Player nemazat ani neupravovať.

**Comment by SimonDrastich** [comment]
Ok

**Comment by SimonDrastich** [comment]
Ok
